version: '2'

networks:
  net_bankingfederation.com:
services:
  ca0:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-partnersbank
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.partnersbank.bankingfederation.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/4d0f7fca3c939461b55eecc63bacb0efaf1640145c960dccad8147929dbe8302_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.partnersbank.bankingfederation.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/4d0f7fca3c939461b55eecc63bacb0efaf1640145c960dccad8147929dbe8302_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/partnersbank.bankingfederation.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerPartnersBank
    networks:
      - net_bankingfederation.com

  ca1:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-multibankwest
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.multibankwest.bankingfederation.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/0719bf2632d3b24b64a11e95ed10804ad2fa948c03220bc23feb60436c75aa94_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.multibankwest.bankingfederation.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/0719bf2632d3b24b64a11e95ed10804ad2fa948c03220bc23feb60436c75aa94_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/multibankwest.bankingfederation.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerMultiBankWest
    networks:
      - net_bankingfederation.com

  orderer.bankingfederation.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.bankingfederation.com
    container_name: orderer.bankingfederation.com
    networks:
      - net_bankingfederation.com

  peer0.partnersbank.bankingfederation.com:
    container_name: peer0.partnersbank.bankingfederation.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.partnersbank.bankingfederation.com
    networks:
      - net_bankingfederation.com

  peer1.partnersbank.bankingfederation.com:
    container_name: peer1.partnersbank.bankingfederation.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.partnersbank.bankingfederation.com
    networks:
      - net_bankingfederation.com

  peer0.multibankwest.bankingfederation.com:
    container_name: peer0.multibankwest.bankingfederation.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.multibankwest.bankingfederation.com
    networks:
      - net_bankingfederation.com

  peer1.multibankwest.bankingfederation.com:
    container_name: peer1.multibankwest.bankingfederation.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.multibankwest.bankingfederation.com
    networks:
      - net_bankingfederation.com
