version: '2'

networks:
  net_bankingfederation.com:

services:

  orderer.bankingfederation.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.bankingfederation.com
    container_name: orderer.bankingfederation.com
    networks:
      - net_bankingfederation.com

  peer0.partnersbank.bankingfederation.com:
    container_name: peer0.partnersbank.bankingfederation.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.partnersbank.bankingfederation.com
    networks:
      - net_bankingfederation.com

  peer1.partnersbank.bankingfederation.com:
    container_name: peer1.partnersbank.bankingfederation.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.partnersbank.bankingfederation.com
    networks:
      - net_bankingfederation.com

  peer0.multibankwest.bankingfederation.com:
    container_name: peer0.multibankwest.bankingfederation.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.multibankwest.bankingfederation.com
    networks:
      - net_bankingfederation.com

  peer1.multibankwest.bankingfederation.com:
    container_name: peer1.multibankwest.bankingfederation.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.multibankwest.bankingfederation.com
    networks:
      - net_bankingfederation.com

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.partnersbank.bankingfederation.com:7051
      - CORE_PEER_LOCALMSPID=PartnersBankMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/bankingfederation.com/crypto/peerOrganizations/partnersbank.bankingfederation.com/peers/peer0.partnersbank.bankingfederation.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/bankingfederation.com/crypto/peerOrganizations/partnersbank.bankingfederation.com/peers/peer0.partnersbank.bankingfederation.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/bankingfederation.com/crypto/peerOrganizations/partnersbank.bankingfederation.com/peers/peer0.partnersbank.bankingfederation.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/bankingfederation.com/crypto/peerOrganizations/partnersbank.bankingfederation.com/users/Admin@partnersbank.bankingfederation.com/msp
    working_dir: /opt/gopath/src/bankingfederation.com
    command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME} ${DELAY}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/bankingfederation.com/chaincode/
        - ./crypto-config:/opt/gopath/src/bankingfederation.com/crypto/
        - ./scripts:/opt/gopath/src/bankingfederation.com/scripts/
        - ./channel-artifacts:/opt/gopath/src/bankingfederation.com/channel-artifacts
    depends_on:
      - orderer.bankingfederation.com
      - peer0.partnersbank.bankingfederation.com
      - peer1.partnersbank.bankingfederation.com
      - peer0.multibankwest.bankingfederation.com
      - peer1.multibankwest.bankingfederation.com
    networks:
      - net_bankingfederation.com

